### ISSUE TITLE
Hi bro, you deleted post on stackoverflow

### ISSUE THREAD

**Issue by h1w** [PrathameshBhatkar/SeaJam-2021--AquaCleaner#1]
I tryed to solve your problem, but you deleted the post.

I think you need to use **Affine Transformations**.

[Affine transformation on wiki][1]

[Affine transformation on OpenCV docs][2]

  [1]: https://en.wikipedia.org/wiki/Affine_transformation
  [2]: https://docs.opencv.org/3.4/d4/d61/tutorial_warp_affine.html

Here is an example:
```
import cv2
import numpy as np

src = cv2.imread('sky.png')
if src is None:
  print('Could not open image')
  exit(0)

srcTri = np.array( [[0, 0], [src.shape[1] - 1, 0], [0, src.shape[0] - 1]] ).astype(np.float32)
dstTri = np.array( [[0, src.shape[1]*0.33], [src.shape[1]*0.85, src.shape[0]*0.25], [src.shape[1]*0.15, src.shape[0]*0.7]] ).astype(np.float32)

warp_mat = cv2.getAffineTransform(srcTri, dstTri)

warp_dst = cv2.warpAffine(src, warp_mat, (src.shape[1], src.shape[0]))

# Rotating the image after Warp
center = (warp_dst.shape[1]//2, warp_dst.shape[0]//2)
angle = -30
scale = 0.6

rot_mat = cv2.getRotationMatrix2D( center, angle, scale )

warp_rotate_dst = cv2.warpAffine(warp_dst, rot_mat, (warp_dst.shape[1], warp_dst.shape[0]))

cv2.imshow('Source image', src)
cv2.imshow('Warp', warp_dst)
cv2.imshow('Warp + Rotate', warp_rotate_dst)

cv2.waitKey()
```

**Comment by PrathameshBhatkar** [comment]
> I tryed to solve your problem, but you deleted the post.
> 
> I think you need to use **Affine Transformations**.
> 
> [Affine transformation on wiki](https://en.wikipedia.org/wiki/Affine_transformation)
> 
> [Affine transformation on OpenCV docs](https://docs.opencv.org/3.4/d4/d61/tutorial_warp_affine.html)
> 
> Here is an example:
> 
> ```
> import cv2
> import numpy as np
> 
> src = cv2.imread('sky.png')
> if src is None:
>   print('Could not open image')
>   exit(0)
> 
> srcTri = np.array( [[0, 0], [src.shape[1] - 1, 0], [0, src.shape[0] - 1]] ).astype(np.float32)
> dstTri = np.array( [[0, src.shape[1]*0.33], [src.shape[1]*0.85, src.shape[0]*0.25], [src.shape[1]*0.15, src.shape[0]*0.7]] ).astype(np.float32)
> 
> warp_mat = cv2.getAffineTransform(srcTri, dstTri)
> 
> warp_dst = cv2.warpAffine(src, warp_mat, (src.shape[1], src.shape[0]))
> 
> # Rotating the image after Warp
> center = (warp_dst.shape[1]//2, warp_dst.shape[0]//2)
> angle = -30
> scale = 0.6
> 
> rot_mat = cv2.getRotationMatrix2D( center, angle, scale )
> 
> warp_rotate_dst = cv2.warpAffine(warp_dst, rot_mat, (warp_dst.shape[1], warp_dst.shape[0]))
> 
> cv2.imshow('Source image', src)
> cv2.imshow('Warp', warp_dst)
> cv2.imshow('Warp + Rotate', warp_rotate_dst)
> 
> cv2.waitKey()
> ```

Thank U for your time
